spring.application.name=scaffolding

##APLICATION PROPERTIES ##
app.name='@project.name@'
app.desc='@project.description@'
app.version='@project.version@'
app.url=http://localhost:8080
app.dev-name=Joaquin Ariel Zabala
app.dev-email=joaquinzabala118@gmail.com